---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sinkserver
  labels:
    app: sinkserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sinkserver
  template:
    metadata:
      labels:
        app: sinkserver
    spec:
      imagePullSecrets:
        - name: hottis-registry-creds
      containers:
        - name: sinkserver
          image: registry.hottis.de/mainscnt/sinkserver:314b9a42
          ports:
            - containerPort: 20169
              protocol: UDP
          env:
            - name: PGHOST
              valueFrom: 
                configMapKeyRef:
                  name: sinkserver-config
                  key: dbhost
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: sinkserver-secret
                  key: dbpass
---
apiVersion: v1
kind: Service
metadata:
  name: sinkserver
  labels:
    app: sinkserver
spec:
  type: LoadBalancer
  selector:
    app: sinkserver
  ports:
    - protocol: UDP
      port: 20169
      targetPort: 20169



